name: 'Generate _sidebar.md'
description: 'generate _sidebar.md to show the file catalog'
inputs:
  github_token:
    description: 'github_token'
    required: true
# outputs:
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: read_catalog.sh > _sidebar.md
      shell: bash
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add _sidebar.md
        status=$(git status --porcelain)
        if [ -z "$status" ]; then
          git commit -m "Add changes"
        else
          echo "There are changes"
        fi
      shell: bash
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}